server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/llm_gateway?serverTimezone=Asia/Kolkata
    username: llm_user
    password: llm_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.springframework.security: DEBUG